set shell=powershell
set shellcmdflag=-command

set ruler                            " show row/column number
set backspace=2                      " backspace works in insert mode
filetype indent on                   " activates indenting for files
filetype plugin on
set relativenumber number            " relative line numbers
set ignorecase smartcase             " case preferences
set nobackup
set tabstop=4 shiftwidth=4 expandtab " tabs & indents size 4, tabkey = spaces
set incsearch showmatch              " search options
set lazyredraw ttyfast               " faster rendering 
syntax on                            " syntax highlighting
set cindent                          " prevent the # mark from unindenting
set cinkeys-=0#
set indentkeys-=0#

" unmap arrow keys to encourage good vim practices
map <Up> <NOP>
map <Down> <NOP>
map <Left> <NOP>
map <Right> <NOP>

" shortcuts
nnoremap   <C-n>  :bn<CR>|                " next buffer
nnoremap   <C-p>  :bp<CR>|                " prev buffer

" Syntax corrections
au BufRead, BufNewFile *.pde setfiletype java " processing syntax highlighting

autocmd FileType make set noexpandtab shiftwidth=8 softtabstop=0

" Git settings
autocmd Filetype gitcommit setlocal spell textwidth=72

" show when I run over 80 columns
set colorcolumn=121
hi ColorColumn ctermbg=darkgray
highlight OverLength ctermbg=red ctermfg=white guibg=#392929
match OverLength /\%121v.\+/

let $cpptemplate = 'c:\templates\t.cpp'
